### ISSUE TITLE
Pass ALL tests

### ISSUE THREAD

**Issue by dginev** [dginev/latexml-oxide#30]
Tracker issue for the first milestone. Goals:

 * pass ALL tests from LaTeXML's `t/` subdirectory
 * Have an integration with latexmlpost, to demo HTML conversion OR a mock post-processor in Rust
 * Have a demo with a Rocket web service, akin to the current showcase at https://latexml.mathweb.org/editor

This would suffice for a `1.0` release of rtx.

**Comment by dginev** [comment]
### Core tests overview (task list)
- [x] ├── 000_hello
- [x]    ├── hello.tex
- [ ] ├── 000_test_context
- [ ] ├── 002_unit_findfile
- [ ] ├── 00_unittest
- [x] ├── 05_tokenize
- [x]    ├── alltt.tex ( #77 )
- [x]    ├── comment.tex ( #2 )
- [x]    ├── equality.tex ( #3 )
- [x]    ├── file_read.tex ( #77 )
- [x]    ├── hashes.tex
- [x]    ├── ligatures.tex ( #14 )
- [x]    ├── mathtokens.tex ( #76 )
- [x]    ├── newlines.tex ( #77 )
- [x]    ├── par.tex
- [x]    ├── percent.tex ( #16 )
- [x]    ├── trailingspaces.tex
- [x]    ├── url.tex ( #17 )
- [x]    ├── verbata.tex ( #20 )
- [x]    └── verb.tex ( #18  )
- [x] ├── 01_expansion
- [x]    ├── aftergroup.tex ( #89 )
- [x]    ├── definedness.tex ( #89 )
- [x]    ├── endinput.tex ( #105 )
- [x]    ├── environments.tex ( #103 )
- [x]    ├── env.tex ( #105 )
- [x]    ├── escapechar.tex
- [x]    ├── etex.tex ( #105 )
- [x]    ├── etoolbox.tex ( #128 )
- [x]    ├── for.tex ( #107 )
- [x]    ├── hyperurls.tex ( #126 )
- [x]    ├── ifthen.tex ( #108 )
- [x]    ├── inin.tex
- [x]    ├── keywords.tex ( #104 )
- [x]    ├── lettercase.tex ( #112 )
- [x]    ├── meaning.tex ( #113 )
- [x]    ├── multi_escaped_param.tex ( #114 )
- [x]    ├── noexpand_conditional.tex ( #106 )
- [x]    ├── noexpand.tex ( #106 )
- [x]    ├── numexpr.tex ( #109 )
- [x]    ├── parindent.tex ( #110 )
- [x]    ├── partial.tex
- [x]    ├── pass_param_toks_in_gen_macros.tex ( #115 )
- [x]    ├── pdftex_expanded.tex ( #116 )
- [x]    ├── romannumeral.tex
- [x]    ├── simple_dimen.tex ( #89 )
- [x]    ├── testchar.tex ( #117 )
- [x]    ├── testexpand.tex ( #89 )
- [x]    ├── testif.tex ( #107 )
- [x]    ├── testinput.tex ( #118 )
- [x]    ├── testmultido.tex ( #119 )
- [x]    ├── textcase.tex ( #125 )
- [x]    ├── toks.tex ( #89 )
- [x]    ├── urls.tex ( #123 )
- [x]    ├── utflettercase.tex ( #124 )
- [x]    ├── whichcache.tex ( #122 )
- [x]    ├── whichinput.tex ( #121 )
- [x] ├── 12_grouping ( #75 )
- [x]    ├── mathgroup.tex
- [x]    ├── scopemacro.tex ( #77 )
- [ ] ├── 170_grammar_coverage
- [x] ├── 20_digestion
- [x]    ├── box.tex ( #38 )
- [x]    ├── chardefs.tex ( #130 )
- [x]    ├── defaultunits.tex ( #32 )
- [x]    ├── def.tex ( #31 )
- [x]    ├── dollar.tex ( #129 )
- [x]    ├── io.tex ( #39, #86)
- [x]    ├── primes.tex ( #35 )
- [x]    ├── rebox.tex ( #133 )
- [x]    ├── testctr.tex ( #34 , #130 )
- [x]    ├── xargs.tex ( #163 )
- [x] ├── 22_fonts ( #201, #202, #203 )
- [x]    ├── abxtest.tex
- [x]    ├── accents.tex
- [x]    ├── acc.tex
- [x]    ├── bbold.tex
- [x]    ├── cancels.tex
- [x]    ├── ding.tex
- [x]    ├── emph.tex
- [x]    ├── esint.tex
- [x]    ├── fonts.tex
- [x]    ├── marvosym.tex
- [x]    ├── mathaccents.tex
- [x]    ├── mathbbol.tex
- [x]    ├── mathcolor.tex
- [x]    ├── mixed.tex
- [x]    ├── omencodings.tex
- [x]    ├── sizes.tex
- [x]    ├── soul.tex
- [x]    ├── stmaryrd.tex
- [x]    ├── textcomp.tex
- [x]    ├── textsymbols.tex
- [x]    ├── ulem.tex
- [x]    ├── wasysym.tex
- [x] ├── 30_encoding ( #36 , #37 , #201, #202, #203)
- [x]    ├── ansinew.tex
- [x]    ├── applemac.tex
- [x]    ├── cp1250.tex
- [x]    ├── cp1252.tex
- [x]    ├── cp437de.tex
- [x]    ├── cp437.tex
- [x]    ├── cp850.tex
- [x]    ├── cp852.tex
- [x]    ├── cp858.tex
- [x]    ├── cp865.tex
- [x]    ├── decmulti.tex
- [x]    ├── latin10.tex
- [x]    ├── latin1.tex
- [x]    ├── latin2.tex
- [x]    ├── latin3.tex
- [x]    ├── latin4.tex
- [x]    ├── latin5.tex
- [x]    ├── latin9.tex
- [x]    ├── ly1.tex
- [x]    ├── ot1.tex
- [x]    ├── t1.tex
- [x]    ├── t2a.tex
- [x]    ├── t2b.tex
- [x]    ├── t2c.tex
- [x]    ├── ts1.tex
- [x]    ├── utf8.tex
- [x] ├── 32_keyval (#201, #202, #203) 
- [x]    ├── keyvalemptyvalue.tex
- [x]    ├── keyvalinline.tex
- [x]    ├── keyvalstyle.tex
- [x]    ├── xkeyvaladv.tex
- [x]    ├── xkeyvalbasic.tex
- [x]    ├── xkeyvalkvcompat.tex
- [x]    ├── xkeyvalstyle.tex
- [x]    ├── xkeyvalview.tex
- [x] ├── 33_keyval_options
- [x]    ├── xkvdop1a.tex
- [x]    ├── xkvdop1b.tex
- [x]    ├── xkvdop2a.tex
- [x]    ├── xkvdop2b.tex
- [x]    ├── xkvdop3a.tex
- [x]    ├── xkvdop3b.tex
- [x]    ├── xkvdop4a.tex
- [x]    ├── xkvdop5a.tex
- [x]    ├── xkvdop5b.tex
- [x]    ├── xkvdop6a.tex
- [x]    ├── xkvdop6b.tex
- [x] ├── 40_math
- [x]    ├── ambiguous_relations.tex
- [x]    ├── array_newline_math.tex
- [ ]    ├── array.tex
- [ ]    ├── arrows.tex
- [ ]    ├── choose.tex
- [ ]    ├── compact_dual.tex
- [ ]    ├── declare.tex
- [ ]    ├── fracs.tex
- [ ]    ├── niceunits.tex
- [ ]    ├── not.tex
- [ ]    ├── sampler.tex
- [ ]    ├── simplemath.tex
- [ ]    ├── testover.tex
- [ ]    ├── testscripts.tex
- [ ] ├── 50_structure
- [x]    ├── abstract.tex ( #40 )
- [x]    ├── acro.tex
- [ ]    ├── amsarticle.tex
- [x]    ├── apps.tex
- [x]    ├── app.tex
- [x]    ├── article.tex ( #144 )
- [ ]    ├── asubfile.tex
- [x]    ├── authors.tex ( #165 )
- [x]    ├── autoref.tex
- [x]    ├── badabstract.tex ( #41 )
- [x]    ├── beforeafter.tex ( #166 )
- [x]    ├── bibsect.tex
- [x]    ├── book.tex ( #168 )
- [x]    ├── changectr.tex
- [x]    ├── columns.tex
- [x]    ├── crazybib.tex
- [x]    ├── csquotes.tex
- [x]    ├── endnote.tex ( #164 )
- [x]    ├── enum.tex
- [x]    ├── epitest.tex
- [ ]    ├── eqnums.tex
- [x]    ├── faketitlepage.tex
- [x]    ├── fancyhdr.tex ( #167 )
- [x]    ├── figures.tex
- [ ]    ├── figure_grids.tex
- [x]    ├── filelist.tex
- [x]    ├── floatnames.tex
- [x]    ├── footnote.tex ( #150 )
- [x]    ├── glossary.tex
- [x]    ├── hyperref.tex ( #150 )
- [ ]    ├── IEEE.tex
- [x]    ├── itemize.tex ( #43 , #85)
- [x]    ├── mainfile.tex
- [x]    ├── natbib.tex
- [x]    ├── options.tex
- [x]    ├── paralists.tex
- [x]    ├── para.tex ( #150 )
- [x]    ├── plainsample.tex ( #164 )
- [x]    ├── report.tex
- [x]    ├── sec.tex ( #44 , #87 )
- [x]    ├── subcaption.tex
- [x]    ├── svabstract.tex
- [x]    ├── titlepage.tex
- [ ] ├── 52_namespace
- [ ]    ├── ns1.tex
- [ ]    ├── ns2.tex
- [ ]    ├── ns3.tex
- [ ]    ├── ns4.tex
- [ ]    ├── ns5.tex
- [ ] ├── 53_alignment
- [ ]    ├── algx.tex
- [x]    ├── array.tex
- [ ]    ├── badeqnarray.tex
- [ ]    ├── cells.tex  
- [ ]    ├── colortbls.tex
- [ ]    ├── diagboxtest.tex
- [ ]    ├── eqnarray.tex
- [x]    ├── halignatt.tex
- [x]    ├── halign.tex
- [x]    ├── listing.tex
- [x]    ├── longtable.tex
- [x]    ├── mathmix.tex
- [x]    ├── min_listings_data.tex
- [x]    ├── min_listing2.tex
- [x]    ├── min_listing.tex
- [x]    ├── min_listing_lang.tex
- [x]    ├── min_listing_string.tex
- [x]    ├── min_listing_display.tex
- [x]    ├── min_listing_short.tex
- [x]    ├── morse.tex
- [ ]    ├── ncases.tex
- [ ]    ├── plainmath.tex
- [ ]    ├── split.tex
- [ ]    ├── supertabular.tex
- [x]    ├── tabtab.tex
- [x]    ├── tabularstar.tex
- [x]    ├── tabular.tex
- [ ]    ├── vmode.tex
- [ ] ├── 55_theorem
- [x]    ├── amstheorem.tex
- [x]    ├── latextheorem.tex
- [ ]    ├── ntheorem.tex
- [x]    ├── ntheoremstyle.tex
- [x]    └── theorem.tex
- [ ] ├── 56_ams
- [ ]    ├── amsdisplay.tex
- [ ]    ├── cd.tex
- [x]    ├── dots.tex
- [x]    ├── genfracs.tex
- [ ]    ├── mathtools.tex
- [ ]    ├── matrix.tex
- [ ]    ├── sideset.tex
- [ ] ├── 65_graphics
- [x]    ├── calc.tex
- [x]    ├── colors.tex
- [x]    ├── framed.tex
- [ ]    ├── graphrot.tex
- [x]    ├── keyval.tex
- [ ]    ├── picture.tex
- [x]    ├── simplekv.tex
- [ ]    ├── xcolors.tex
- [ ]    ├── xytest.tex
- [x] ├── 700_unit_parse
- [x]    ├── recognizer_subscript_atom
- [x]    ├── recognizer_after_failure
- [x]    ├── basic_1 
- [ ] ├── 70_parse
- [ ]    ├── algebraic_terms.tex
- [ ]    ├── array_math.tex
- [ ]    ├── artefacts.tex
- [ ]    ├── calculus.tex
- [ ]    ├── compose.tex
- [ ]    ├── fences.tex
- [ ]    ├── function_argument_syntax.tex
- [ ]    ├── functions.tex
- [ ]    ├── kludge.tex
- [ ]    ├── metarelation_elision.tex
- [ ]    ├── mixedfrac.tex
- [ ]    ├── multirelations.tex
- [ ]    ├── nested_application.tex
- [ ]    ├── operators.tex
- [ ]    ├── parens.tex
- [ ]    ├── parser_speculate.tex
- [ ]    ├── prescripted.tex
- [ ]    ├── qm.tex
- [ ]    ├── relations.tex
- [ ]    ├── scripts.tex
- [ ]    ├── sequences_and_lists.tex
- [ ]    ├── sets.tex
- [ ]    ├── spacing.tex
- [ ]    ├── standalone_equations.tex
- [ ]    ├── standalone_modifiers.tex
- [ ]    ├── subordinate_lists.tex
- [ ]    ├── terms.tex
- [ ]    ├── vertbars.tex
- [ ] ├── 80_complex
- [ ]    ├── acm_aria.tex
- [x]    ├── aastex_test.tex
- [x]    ├── aastex631_deluxetable.tex
- [ ]    ├── aliceblog.tex
- [ ]    ├── cleveref_minimal.tex
- [ ]    ├── equationnest.tex
- [x]    ├── hyperchars.tex
- [ ]    ├── labelled.tex
- [ ]    ├── physics.tex
- [ ]    ├── si.tex
- [ ]    ├── tcilatex_minimal.tex
- [ ]    ├── versioned_fallback.tex
- [x]    ├── xii.tex ( #26 )
- [ ] ├── 81_babel
- [ ]    ├── csquotes.tex
- [ ]    ├── french.tex
- [ ]    ├── german.tex
- [ ]    ├── greek.tex
- [ ]    ├── numprints.tex
- [ ]    ├── page545.tex
- [ ] ├── 82_moderncv
- [ ]    ├── cs_cv.tex
- [ ]    ├── orc.tex
- [ ] ├── 83_expl3
- [ ]    ├── tilde_tricks.tex
- [ ]    ├── xparse.tex
- [ ] ├── 84_slides
- [ ]    ├── beamer.tex
- [ ]    ├── slides.tex
- [ ] ├── 85_pgf
- [ ]    ├── stress_pgfmath.tex
- [ ]    ├── stress_pgfplots.tex
- [ ] ├── 86_tikz
- [ ]    ├── ac_drive_components.tex
- [ ]    ├── ac_drive_voltage.tex
- [ ]    ├── atoms_and_orbitals.tex
- [ ]    ├── consort_flowchart.tex
- [ ]    ├── cycle.tex
- [ ]    ├── dominoes.tex
- [ ]    ├── tikz_3d_cone.tex
- [ ]    ├── tikz_figure.tex
- [ ]    ├── unit_tests_by_silviu.tex
- [ ]    ├── various_colors.tex

Deferred:

(Note: `9*_` test sets go beyond Core coverage, and are intended for the following milestone )

**Comment by dginev** [comment]
cc @brucemiller , a very visual illustration of my progress on the test suite can be seen in the comment above. It is intended as a whitelist - I actually haven't attempted all tests yet, proceeding in a one-by-one fashion. So some of the unmarked entries could already pass, or be just a simple copy-paste of a binding away from passing. Others require math parsing, and other infrastructure, naturally.

At the time of writing this comment, rtx is passing  with certainty 15 of 207 core tests from latexml.

**Comment by dginev** [comment]
We are at 26% active passing tex-to-xml tests as of Jun 2024. In absolute terms, 72 of 278.

**Comment by dginev** [comment]
We are at **61%** active passing tex-to-xml tests as of March 2026. In absolute terms, 207 of 338.

This number is a little slippery since not all tests are portable directly, but it definitely covers our core TeX coverage test (the essential `.tex` files in `LaTeXML/t/`).

For context: There was a massive upward coverage spike over the course of 1 week, using Claude Opus 4.6 "heavy effort". We are now at ~90,000 lines of Rust (~75k of them code) in the project.

**Comment by tkw1536** [comment]
Out of interest:
- Did the uptick in tests passes make the rust implementation slower?
- Once you have all tests passing (which doesn't seem too far off now, congrats), are you planning on running all of ArXiv to see how the implementation behaves on real-world documents?

**Comment by dginev** [comment]
Thanks for the interest! Glad that you're still tracking this "pie in the sky" project.

### Performance 

I can anecdotally say that the claude-generated code is often a little quick to `.clone()` or `.to_string()`. I anticipate a "performance optimization" session at the end where we also do a large round of refactoring that speeds things up. The Rust compiler messages are a really great aid for that - similar to how Lean aids autoformalization work.

As of March 21, I see the following times (`Intel Core i7-12800H` chip on my laptop):
 - 10 seconds - fetching crates.io dependencies to start compilation
 - 65 seconds - compilation via `cargo build --release`
 - 2.5 seconds - passing 255 tests via `cargo test --release --tests` 

As a single test, `structure/article.tex` converts in `0.092s` in Rust vs `1.949s` in Perl. So I think no noticeable slowdown yet. Btw, pdflatex runs on this example in `0.194s`.

### Plan to scale testing

Indeed, I believe the LaTeXML tests are wonderful to have, but aren't quite enough to guarantee the port is exhaustive. Running against arXiv sandboxes will be a next phase of testing, and running against all of arXiv would be the last. But there are many unknowns on the way for me to confidently say that we will get there. I am certainly trying to...

An equally exciting fact has been that the Perl LaTeXML can benefit from the same "superhuman" AI agent that the Rust port has benefited from. At the least it is faster and mostly better than me at deep kernel debugging. That adds yet another possible step forward - after we get to the level of Perl's LaTeXML, we could continue advancing to TeX parity with more AI assistance. It is somewhat encouraging that it looks possible to remove the "Deyan bottleneck", though it is also concerning that long-term this doesn't remove Deyan altogether :-)

**Comment by dginev** [comment]
This issue has served its purpose and is ready to be closed.

Initially it was tracking my manual development of tests passing. Now that the work is fully automated it is somewhat less useful.


I suspect we still have work on the test suite - refining the XML in cases where there are inevitable differences (e.g. math parsing), definitely growing with a lot more tests extracted from arXiv failures, as well as continually checking the model didn't "cheat" in some new way - e.g. by forgetting to re-add a test after debugging. But each of these would be better served in new github tickets.
